# Generated by Django 3.2.25 on 2025-01-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=45)),
                ('descriptiom', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('days', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'package',
                'managed': False,
            },
        ),
    ]
