# Generated by Django 3.2.25 on 2025-01-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('place', models.CharField(max_length=45)),
                ('phone_number', models.CharField(db_column='phone number', max_length=45)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
    ]
