# Generated by Django 3.2.25 on 2025-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
