# Generated by Django 3.2.25 on 2025-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('itinerary_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('destination', models.CharField(max_length=45)),
                ('days', models.IntegerField()),
                ('budget', models.IntegerField()),
            ],
            options={
                'db_table': 'itinerary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('planid', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
    ]
